import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigModule, ConfigService } from '@nestjs/config';
import {
  UserProfile,
  AdvertiserCard,
  InfluencerCard,
  AutoCampaign,
  Offer,
  Application,
  Review,
  PaymentRequest,
  Blacklist,
  Favorite,
  Conversation,
  Message,
  UserSettings,
  RateLimitInteraction,
  UserRoleAssignment,
  ContentReport,
  ModerationQueue,
  AdminLog,
  ContentFilter,
  SupportTicket,
  SupportMessage,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        type: 'postgres',
        host: configService.get('DB_HOST'),
        port: configService.get('DB_PORT', 5432),
        username: configService.get('DB_USERNAME'),
        password: configService.get('DB_PASSWORD'),
        database: configService.get('DB_DATABASE'),
        entities: [
          UserProfile,
          AdvertiserCard,
          InfluencerCard,
          AutoCampaign,
          Offer,
          Application,
          Review,
          PaymentRequest,
          Blacklist,
          Favorite,
          Conversation,
          Message,
          UserSettings,
          RateLimitInteraction,
          UserRoleAssignment,
          ContentReport,
          ModerationQueue,
          AdminLog,
          ContentFilter,
          SupportTicket,
          SupportMessage,
        ],
        synchronize: false,
        logging: configService.get('NODE_ENV') === 'development',
        ssl: configService.get('DB_SSL') === 'true' ? { rejectUnauthorized: false } : false,
      }),
      inject: [ConfigService],
    }),
  ],
})
export class DatabaseModule {}
